version: '3'
services:
  postgresql:
    image: postgres
    container_name: mm2d-dev-postgresql
    ports:
      - "5433:5432"
    networks:
      - mm2d-dev-net
    environment:
      - POSTGRES_PASSWORD=postgres
  elixir:
    build: 
      context: .
      dockerfile: ElixirDockerfile
    container_name: mm2d-dev-elixir
    stdin_open: true
    tty: true
    ports:
      - "4000:4000"
    depends_on:
      - postgresql
    networks:
      - mm2d-dev-net
    command: >
      bash -c "mix ecto.create
      && mix ecto.migrate
      && mix phx.server"
    volumes:
      - .:/app
    working_dir: /app

networks:
  mm2d-dev-net:
    driver: bridge
